// Author: Conrad Fay
// Problem: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//          1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//          By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <iostream>

void fib(int &first, int &second, int &sum) {
  int tmp = second;
  second = (first + second);
  first = tmp;

  if (second > 4000000)
    return;
  else {
    if ((second % 2) == 0)
      sum+=second;
    fib(first, second, sum);
  }
}

int main() {
  int first = 1;
  int second = 2; 
  int sum = 2;
  
  fib(first, second, sum);

  std::cout << sum << std::endl;
  
  return (0);
}
